// Bridge C++ <-> Rust via bcad-ffi.
//
// This is the only place the two languages meet. The `Bc*` types come from
// `rust/crates/bcad-ffi/include/bcad_ffi.h`, which is generated by hand from the
// crate and pinned to it by a test; nothing here re-declares them.
//
// Ownership, restated because it is the whole risk of this file: Rust hands out
// owned memory. Every `BcString` is copied into a `std::string` and released
// with `bcad_string_free`; every array is released with its matching `_free`,
// which walks the array and releases the strings inside it; the parse handle is
// released on every path out, including the error ones.

#include "bcad/io/DxfBridge.h"

#include "bcad/io/DxfWriter.h"
#include "bcad/layers/LayerManager.h"
#include "bcad/properties/PropertyMap.h"

#include <algorithm>
#include <cstddef>
#include <filesystem>
#include <fstream>
#include <optional>
#include <sstream>
#include <string>
#include <utility>
#include <vector>

#ifdef BCAD_ENABLE_RUST
#include <bcad_ffi.h>
#endif

namespace bcad::io {

namespace {

/// Copies a `BcString` into a `std::string` without releasing it.
///
/// For the elements of an array: the matching `_free` walks the array and
/// releases the strings inside it, so freeing one here would be a double free.
std::string copyString(BcString s) {
    if (s.ptr == nullptr) {
        return {};
    }
    return std::string(s.ptr, s.len);
}

/// Copies a `BcString` and releases the Rust allocation.
///
/// Only for a string the caller owns outright, such as the `error_message` of a
/// failed call. A null `ptr` yields an empty string: the ABI uses a null string
/// for "absent", and an absent name is the same thing as an empty one.
std::string takeString(BcString s) {
    std::string out = copyString(s);
    bcad_string_free(s);
    return out;
}

/// Maps the ABI's `line_type` code to the C++ enum explicitly.
///
/// A `static_cast` would work today only because the two enums happen to be
/// declared in the same order. Reordering either one would then silently give
/// every layer the wrong line type, so the mapping is spelled out and the
/// unknown case is reported rather than guessed.
std::optional<layers::Layer::LineType> toLineType(int code) {
    switch (code) {
        case BCAD_LINETYPE_CONTINUOUS:
            return layers::Layer::LineType::Continuous;
        case BCAD_LINETYPE_DASHED:
            return layers::Layer::LineType::Dashed;
        case BCAD_LINETYPE_DOTTED:
            return layers::Layer::LineType::Dotted;
        case BCAD_LINETYPE_DASHDOT:
            return layers::Layer::LineType::DashDot;
        default:
            return std::nullopt;
    }
}

BcParseOptions toFfiOptions(const DxfBridgeOptions& options) {
    BcParseOptions ffi{};
    ffi.recovery_mode = static_cast<int>(options.recovery_mode);
    ffi.max_file_size = static_cast<unsigned long>(options.max_file_size);
    ffi.max_entities = static_cast<unsigned long>(options.max_entities);
    ffi.timeout_ms = static_cast<unsigned long>(options.timeout_ms);
    return ffi;
}

/// Turns a failed parse into a result, releasing whatever Rust allocated.
///
/// Rust always supplies a message, but a null one must not leave the caller with
/// an empty `error_message` and no way to tell what went wrong, so the code
/// stands in when the text is missing.
DxfBridgeResult failure(BcErrorCode code, BcString message) {
    DxfBridgeResult result;
    result.success = false;
    result.error_message = takeString(message);
    if (result.error_message.empty()) {
        result.error_message =
            "bcad-ffi failed with code " + std::to_string(static_cast<int>(code)) +
            " and no message";
    }
    return result;
}

/// Copies the parse handle's diagnostics out, then frees the Rust array.
///
/// An error-severity diagnostic does not make this a failure: under `Recover`
/// the parse returning a result *and* reporting errors is the documented
/// behaviour, and the caller decides what to do about it via `hasErrors`.
void collectDiagnostics(ParsedDxfHandle* handle, DxfBridgeResult& result) {
    BcDiagnostic* diagnostics = nullptr;
    unsigned long count = 0;
    if (bcad_dxf_get_diagnostics(handle, &diagnostics, &count) != BCAD_OK) {
        return;
    }
    if (diagnostics == nullptr) {
        return;
    }
    result.diagnostics.reserve(static_cast<std::size_t>(count));
    for (unsigned long i = 0; i < count; ++i) {
        result.diagnostics.push_back(DxfBridgeDiagnostic{
            .severity = diagnostics[i].severity,
            .code = copyString(diagnostics[i].code),
            .message = copyString(diagnostics[i].message),
            .suggestion = copyString(diagnostics[i].suggestion),
        });
    }
    bcad_diagnostics_free(diagnostics, count);
}

/// Creates the parsed layers in `document`.
///
/// Returns the number actually created. Layer "0" is skipped: `LayerManager`
/// creates it, and it cannot be removed, so writing to it would be the only way
/// to give the imported file the layer its own default colour. Every other layer
/// is created or updated, which is why an existing name is not an error.
std::size_t importLayers(ParsedDxfHandle* handle,
                         core::Document& document,
                         DxfBridgeResult& result) {
    BcLayer* layers = nullptr;
    unsigned long count = 0;
    if (bcad_dxf_get_layers(handle, &layers, &count) != BCAD_OK || layers == nullptr) {
        return 0;
    }

    std::size_t imported = 0;
    for (unsigned long i = 0; i < count; ++i) {
        const BcLayer& layer = layers[i];
        std::string name = copyString(layer.name);

        if (name == "0") {
            // Already present and indestructible; leave it as the document made it.
            continue;
        }
        if (name.empty()) {
            result.diagnostics.push_back(DxfBridgeDiagnostic{
                .severity = 2,
                .code = "BRIDGE-LAYER-001",
                .message = "a layer table entry has no name and was skipped",
                .suggestion = "",
            });
            continue;
        }
        if (const auto lineType = toLineType(layer.line_type); !lineType.has_value()) {
            result.diagnostics.push_back(DxfBridgeDiagnostic{
                .severity = 1,
                .code = "BRIDGE-LAYER-002",
                .message = "layer '" + name + "' has an unknown line type; using Continuous",
                .suggestion = "",
            });
        }

        // `createLayer` returns the existing layer when the name is already
        // there, so an update is a plain assignment on the result.
        layers::Layer& target = document.layerManager().createLayer(
            name, geom::Color{layer.color_r, layer.color_g, layer.color_b, 1.0f});
        target.lineWeight = layer.line_weight;
        target.visible = layer.visible != 0;
        target.locked = layer.locked != 0;
        target.lineType = toLineType(layer.line_type).value_or(layers::Layer::LineType::Continuous);
        ++imported;
    }

    bcad_layers_free(layers, count);
    return imported;
}

/// Shared tail of both entry points, once a parse has succeeded.
DxfBridgeResult finish(ParsedDxfHandle* handle, BcDxfParseResult& parsed) {
    DxfBridgeResult result;
    result.success = true;
    result.parsed_entity_count = parsed.entity_count;
    result.parsed_layer_count = parsed.layer_count;
    result.document = std::make_unique<core::Document>();

    // Diagnostics first: a layer import can add to the list, and the parser's
    // own messages are the reason a caller would be looking.
    collectDiagnostics(handle, result);
    result.imported_layer_count = importLayers(handle, *result.document, result);

    // `finish` is only reached with a live handle, and every path out of the
    // callers releases it exactly once.
    bcad_dxf_free(handle);
    return result;
}

}  // namespace

DxfBridgeResult readDxfFromFile(const std::string& path, DxfBridgeOptions options) {
#ifdef BCAD_ENABLE_RUST
    const BcParseOptions ffi_options = toFfiOptions(options);

    BcDxfParseResult parsed{};
    const BcErrorCode code = bcad_dxf_parse_file(path.c_str(), &ffi_options, &parsed);
    if (code != BCAD_OK) {
        return failure(code, parsed.error_message);
    }
    return finish(parsed.handle, parsed);
#else
    (void)path;
    (void)options;
    DxfBridgeResult result;
    result.success = false;
    result.error_message = "DXF import not available: Rust support disabled";
    return result;
#endif
}

DxfBridgeResult readDxfFromBytes(const std::vector<std::uint8_t>& data,
                                 DxfBridgeOptions options) {
#ifdef BCAD_ENABLE_RUST
    const BcParseOptions ffi_options = toFfiOptions(options);

    BcDxfParseResult parsed{};
    const BcErrorCode code =
        bcad_dxf_parse_bytes(data.data(), data.size(), &ffi_options, &parsed);
    if (code != BCAD_OK) {
        return failure(code, parsed.error_message);
    }
    return finish(parsed.handle, parsed);
#else
    (void)data;
    (void)options;
    DxfBridgeResult result;
    result.success = false;
    result.error_message = "DXF import not available: Rust support disabled";
    return result;
#endif
}

DxfBridgeResult readDxfMetadataFromFile(const std::string& path, DxfBridgeOptions options) {
#ifdef BCAD_ENABLE_RUST
    const BcParseOptions ffi_options = toFfiOptions(options);

    BcDxfParseResult parsed{};
    const BcErrorCode code = bcad_dxf_parse_file(path.c_str(), &ffi_options, &parsed);
    if (code != BCAD_OK) {
        // `fail_parse` on the Rust side nulls the handle and gives the message,
        // so there is nothing to free beyond the message itself.
        return failure(code, parsed.error_message);
    }
    return finish(parsed.handle, parsed);
#else
    (void)path;
    (void)options;
    DxfBridgeResult result;
    result.success = false;
    result.error_message = "DXF import not available: Rust support disabled";
    return result;
#endif
}

DxfBridgeResult readDxfMetadataFromBytes(const std::vector<std::uint8_t>& data,
                                         DxfBridgeOptions options) {
#ifdef BCAD_ENABLE_RUST
    const BcParseOptions ffi_options = toFfiOptions(options);

    BcDxfParseResult parsed{};
    const BcErrorCode code =
        bcad_dxf_parse_bytes(data.data(), data.size(), &ffi_options, &parsed);
    if (code != BCAD_OK) {
        return failure(code, parsed.error_message);
    }
    return finish(parsed.handle, parsed);
#else
    (void)data;
    (void)options;
    DxfBridgeResult result;
    result.success = false;
    result.error_message = "DXF import not available: Rust support disabled";
    return result;
#endif
}

bool hasErrors(const DxfBridgeResult& result) {
    return std::any_of(result.diagnostics.begin(), result.diagnostics.end(),
                       [](const DxfBridgeDiagnostic& d) { return d.severity >= 2; });
}

DxfWriteResult writeDxfToFile(const core::Document& doc, const std::string& path) {
#ifdef BCAD_ENABLE_RUST
    DxfWriteResult result;
    result.success = false;

    // Serialize Document to DXF string using existing C++ writer
    std::ostringstream dxfStream;
    if (!writeDxfToStream(doc, dxfStream)) {
        result.error_message = "Failed to serialize Document to DXF";
        return result;
    }
    std::string dxfText = dxfStream.str();

    // Parse DXF text with Rust parser to get handle
    BcParseOptions ffi_options{};
    ffi_options.recovery_mode = 1; // Recover
    ffi_options.max_file_size = 100 * 1024 * 1024;
    ffi_options.max_entities = 1000000;
    ffi_options.timeout_ms = 0;

    BcDxfParseResult parsed{};
    BcErrorCode code = bcad_dxf_parse_bytes(
        reinterpret_cast<const unsigned char*>(dxfText.data()),
        dxfText.size(),
        &ffi_options,
        &parsed
    );

    if (code != BCAD_OK) {
        result.error_message = "Failed to parse DXF for export: " + takeString(parsed.error_message);
        return result;
    }

    // Write using Rust exporter
    code = bcad_dxf_write_file(parsed.handle, path.c_str());
    bcad_dxf_free(parsed.handle);

    if (code != BCAD_OK) {
        result.error_message = "Rust DXF write failed: " + std::to_string(static_cast<int>(code));
        return result;
    }

    result.success = true;
    return result;
#else
    (void)doc;
    (void)path;
    DxfWriteResult result;
    result.success = false;
    result.error_message = "DXF export not available: Rust support disabled";
    return result;
#endif
}

DxfWriteResult writeDxfToBytes(const core::Document& doc, std::vector<std::uint8_t>& outData) {
    DxfWriteResult result;
    result.success = false;

    // Serialize to temporary file, then read back
    // (Simpler approach: write to temp file, read bytes)
    std::string tempPath = std::filesystem::temp_directory_path() / "bcad_dxf_export_XXXXXX.dxf";
    // Use mkstemp equivalent
    int fd = -1;
    {
        std::string templatePath = std::filesystem::temp_directory_path().string() + "/bcad_dxf_export_XXXXXX.dxf";
        std::vector<char> templateVec(templatePath.begin(), templatePath.end());
        templateVec.push_back('\0');
        fd = mkstemp(templateVec.data());
        if (fd == -1) {
            result.error_message = "Failed to create temporary file";
            return result;
        }
        tempPath = templateVec.data();
    }

    DxfWriteResult fileResult = writeDxfToFile(doc, tempPath);
    if (!fileResult.success) {
        if (fd != -1) close(fd);
        std::filesystem::remove(tempPath);
        return fileResult;
    }

    // Read file into bytes
    std::ifstream in(tempPath, std::ios::binary);
    if (!in) {
        result.error_message = "Failed to read temporary DXF file";
        std::filesystem::remove(tempPath);
        if (fd != -1) close(fd);
        return result;
    }
    outData.assign(std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>());
    in.close();

    std::filesystem::remove(tempPath);
    if (fd != -1) close(fd);

    result.success = true;
    return result;
}

#ifdef BCAD_ENABLE_RUST
ValidationReport validateDocument(const core::Document& doc, const ValidationOptions& options) {
    ValidationReport result;
    result.success = false;

    // We need the parse handle from the Rust side to validate
    // This requires serializing the document to DXF and re-parsing
    // (similar to how writeDxfToFile works)
    std::ostringstream dxfStream;
    if (!writeDxfToStream(doc, dxfStream)) {
        result.error_message = "Failed to serialize Document to DXF";
        return result;
    }
    std::string dxfText = dxfStream.str();

    // Parse DXF text with Rust parser to get handle
    BcParseOptions ffi_options{};
    ffi_options.recovery_mode = 1; // Recover
    ffi_options.max_file_size = 100 * 1024 * 1024;
    ffi_options.max_entities = 1000000;
    ffi_options.timeout_ms = 0;

    BcDxfParseResult parsed{};
    BcErrorCode code = bcad_dxf_parse_bytes(
        reinterpret_cast<const unsigned char*>(dxfText.data()),
        dxfText.size(),
        &ffi_options,
        &parsed
    );

    if (code != BCAD_OK) {
        result.error_message = "Failed to parse DXF for validation: " + takeString(parsed.error_message);
        return result;
    }

    // Convert ValidationOptions to FFI format
    BcValidationOptions ffi_opts{};
    ffi_opts.check_self_intersection = options.check_self_intersection ? 1 : 0;
    ffi_opts.check_degenerate = options.check_degenerate ? 1 : 0;
    ffi_opts.check_duplicate_points = options.check_duplicate_points ? 1 : 0;
    ffi_opts.check_overlap = options.check_overlap ? 1 : 0;
    ffi_opts.tolerance = options.tolerance;
    ffi_opts.parallel = options.parallel ? 1 : 0;

    // Call Rust validation
    BcValidationReport ffi_report{};
    code = bcad_validate_dxf(parsed.handle, &ffi_opts, &ffi_report);
    bcad_dxf_free(parsed.handle);

    if (code != BCAD_OK) {
        result.error_message = "Rust validation failed: " + std::to_string(static_cast<int>(code));
        return result;
    }

    if (!ffi_report.success) {
        result.error_message = copyString(ffi_report.error_message);
        return result;
    }

    // Convert FFI issues to C++ structs
    result.issues.reserve(ffi_report.issue_count);
    if (ffi_report.issues != nullptr && ffi_report.issue_count > 0) {
        for (unsigned long i = 0; i < ffi_report.issue_count; ++i) {
            const BcValidationIssue& ffi_issue = ffi_report.issues[i];
            ValidationIssue issue;
            issue.severity = static_cast<ValidationSeverity>(ffi_issue.severity);
            issue.code = copyString(ffi_issue.code);
            issue.message = copyString(ffi_issue.message);
            issue.entity_id = ffi_issue.entity_id;
            issue.has_entity_id = ffi_issue.has_entity_id != 0;
            result.issues.push_back(std::move(issue));
        }
    }

    // Free FFI report
    bcad_validation_report_free(&ffi_report);

    result.success = true;
    return result;
#else
    (void)doc;
    (void)options;
    ValidationReport result;
    result.success = false;
    result.error_message = "Validation not available: Rust support disabled";
    return result;
#endif
}

// --- Database bridge ------------------------------------------------------

DatabaseBridgeResult openDatabase(const std::string& path, bool readonly) {
    DatabaseBridgeResult result;

    BcDbOpenResult opened{};
    const BcErrorCode code = bcad_db_open(path.c_str(), readonly ? 1 : 0, &opened);
    if (code != BCAD_OK) {
        result.error_message = takeString(opened.error_message);
        return result;
    }

    result.success = true;
    result.handle = opened.handle;
    return result;
}

void closeDatabase(void* handle) {
    bcad_db_close(static_cast<DatabaseHandle*>(handle));
}

std::size_t databaseLayerCount(void* handle) {
    if (handle == nullptr) {
        return 0;
    }
    unsigned long count = 0;
    const BcErrorCode code =
        bcad_db_layer_count(static_cast<DatabaseHandle*>(handle), &count);
    return code == BCAD_OK ? static_cast<std::size_t>(count) : 0;
}

std::size_t databaseEntityCount(void* handle) {
    if (handle == nullptr) {
        return 0;
    }
    unsigned long count = 0;
    const BcErrorCode code =
        bcad_db_entity_count(static_cast<DatabaseHandle*>(handle), &count);
    return code == BCAD_OK ? static_cast<std::size_t>(count) : 0;
}

int databaseSchemaVersion(void* handle) {
    if (handle == nullptr) {
        return -1;
    }
    int version = 0;
    const BcErrorCode code =
        bcad_db_schema_version(static_cast<DatabaseHandle*>(handle), &version);
    return code == BCAD_OK ? version : -1;
}

}  // namespace bcad::io
